# Generated by Django 5.1.6 on 2025-02-17 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('tds', models.FloatField(blank=True, null=True)),
                ('hydroponics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='hydroponics.hydroponics')),
            ],
            options={
                'db_table': 'sensor_reading',
            },
        ),
    ]
