# Generated by Django 5.1.6 on 2025-02-18 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0003_hydroponics_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hydroponics',
            index=models.Index(fields=['created'], name='hydroponics_created_7e2fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='hydroponics',
            index=models.Index(fields=['owner'], name='hydroponics_owner_i_1af1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['created'], name='sensor_read_created_d176ab_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['hydroponics'], name='sensor_read_hydropo_47683b_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['ph'], name='sensor_read_ph_83c560_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['temperature'], name='sensor_read_tempera_26e5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['tds'], name='sensor_read_tds_29b7a1_idx'),
        ),
    ]
